name: Scheduled Adjarabet Script

on:
  schedule:
    - cron: '1 0,12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Init npm project (если package.json нет)
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install Playwright
        run: npm install playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run script
        run: npm start
