name: Scheduled Adjarabet Script

on:
  schedule:
    - cron: '1 20,8 * * *'  # Запуск каждый день в 00:01 и 12:01 по Еревану (GMT+4)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ensure npm project initialized
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run script
        run: npm start
